version: '3.8'

services:
  nodejs:
    image: 988698481528.dkr.ecr.ap-south-1.amazonaws.com/task-manager-nodejs:latest
    container_name: task-nodejs
    environment:
      - DB_HOST=${RDS_HOST}
      - DB_USER=${RDS_USER}
      - DB_PASSWORD=${RDS_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BACKEND_NAME=Node.js
    ports:
      - "3001:3001"
    networks:
      - task-network
    restart: unless-stopped

  fastapi:
    image: 988698481528.dkr.ecr.ap-south-1.amazonaws.com/task-manager-fastapi:latest
    container_name: task-fastapi
    environment:
      - DB_HOST=${RDS_HOST}
      - DB_USER=${RDS_USER}
      - DB_PASSWORD=${RDS_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BACKEND_NAME=FastAPI
    ports:
      - "8000:8000"
    networks:
      - task-network
    restart: unless-stopped

  springboot:
    image: 988698481528.dkr.ecr.ap-south-1.amazonaws.com/task-manager-springboot:latest
    container_name: task-springboot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${RDS_HOST}:3306/${DB_NAME}?useSSL=false
      - SPRING_DATASOURCE_USERNAME=${RDS_USER}
      - SPRING_DATASOURCE_PASSWORD=${RDS_PASSWORD}
      - BACKEND_NAME=SpringBoot
    ports:
      - "8080:8080"
    networks:
      - task-network
    restart: unless-stopped

  dotnet:
    image: 988698481528.dkr.ecr.ap-south-1.amazonaws.com/task-manager-dotnet:latest
    container_name: task-dotnet
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=${RDS_HOST};Database=${DB_NAME};User=${RDS_USER};Password=${RDS_PASSWORD};
      - BACKEND_NAME=.NET
    ports:
      - "5000:5000"
    networks:
      - task-network
    restart: unless-stopped

  nginx:
    image: 988698481528.dkr.ecr.ap-south-1.amazonaws.com/task-manager-nginx:latest
    container_name: task-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodejs
      - fastapi
      - springboot
      - dotnet
    networks:
      - task-network
    restart: unless-stopped

networks:
  task-network:
    driver: bridge